services:

  grpc-server:
    ports:
      - "50051:50051"
    build:
      context: .
      dockerfile: Dockerfile

  grpc-server-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVOY_CONFIG: ./envoy/envoy.yaml
    ports:
      - "8080:8080"

#  grpc-client:
#    build:
#      context: .
#      dockerfile: Dockerfile-client