services:
  grpc-server:
    container_name: "grpc-server"
    networks:
      - envoy-server-network
    build:
      context: .
      dockerfile: Dockerfile-server

  envoy-proxy:
    networks:
      - envoy-server-network
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile-envoy

networks:
  envoy-server-network:
    driver: bridge

#  grpc-client:
#    build:
#      context: .
#      dockerfile: Dockerfile-envoy-client