# syntax=docker/dockerfile:1
FROM golang:1.21.1

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum  ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy
COPY server ./
COPY instancepb ./instancepb


# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /grpc-server

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile-envoy what ports
# the application is going to listen on by default.
# https://docs.docker.com/engine/reference/builder/#expose
EXPOSE 50051

# Run
CMD ["/grpc-server"]

#docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 3369f86f493

#- localhostte tarayıcı client ile örnek
#- docker de tamamen kopyalaya yapistir ornek